# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssmh < Formula
  desc "Show the history of connections to Amazon EC2 instances using AWS Session Manager"
  homepage "https://github.com/michimani/ssmh"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/michimani/ssmh/releases/download/v0.1.0/ssmh_0.1.0_darwin_x86_64.tar.gz"
      sha256 "64ee962a03f177a22dbbb0ef64f0977a96882bf38a01e58bc25e994416508297"

      def install
        bin.install "ssmh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/michimani/ssmh/releases/download/v0.1.0/ssmh_0.1.0_darwin_arm64.tar.gz"
      sha256 "8784016f546a9d1de873f0b842d0dbacb9b012108c8bfec92d8957673323df00"

      def install
        bin.install "ssmh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/michimani/ssmh/releases/download/v0.1.0/ssmh_0.1.0_linux_x86_64.tar.gz"
      sha256 "9244232dbf0a73829808ff409be850ee544ac9aa6ba17d1fbe3d89734c037717"

      def install
        bin.install "ssmh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michimani/ssmh/releases/download/v0.1.0/ssmh_0.1.0_linux_arm64.tar.gz"
      sha256 "5bf3e86bdf045e011f959e3f01b3f69e41670e4db5036009d30e38474637427e"

      def install
        bin.install "ssmh"
      end
    end
  end
end
